### ISSUE TITLE
How to set to support the other language(such as Chinese, )

### ISSUE THREAD

**Issue by ZHULOO** [randy3k/radian#176] opened 2020-04-25 14:55 UTC
When I use the radian to plot , the title language is chinese, there are some warnings, I think it may be the encoding problem, so how to set the encoding = utf-8 ?

**Comment by randy3k** [comment] 2020-04-25 17:28
Could you be more specific? What kind of warnings you encountered?

**Comment by ZHULOO** [comment] 2020-04-26 11:07
![20200426190543](https://user-images.githubusercontent.com/43084101/80305724-240e3380-87f1-11ea-85f3-080ea6d84f8c.png)
![20200426190611](https://user-images.githubusercontent.com/43084101/80305726-27a1ba80-87f1-11ea-859c-55d9bb5fbd38.png)

**Comment by randy3k** [comment] 2020-04-26 17:39
<img width="1002" alt="Screen Shot 2020-04-26 at 10 38 36 AM" src="https://user-images.githubusercontent.com/1690993/80315046-1b463f00-87aa-11ea-9a2e-3be4667efbf5.png">

It is running fine on my English windows though.

**Comment by randy3k** [comment] 2020-04-26 18:15
And it seems that it is still working even if I change my display language to Chinese. Not sure what is causing your warnings.

**Comment by randy3k** [comment] 2020-04-26 18:18
What is the value of `Sys.getlocale()`?

**Comment by ZHULOO** [comment] 2020-04-27 01:53
Thanks, When I run `plot(0,main = "窗前明月光")`, It works fine indeed,but with an extra line of error "There were 15 warnings (use warnings() to see them) " 
![20200427093753](https://user-images.githubusercontent.com/43084101/80326615-f4504180-886b-11ea-8a57-bee51f166178.png)
![20200427093830](https://user-images.githubusercontent.com/43084101/80326618-f5816e80-886b-11ea-8bc8-5aac85dd0bcb.png)
 The `Sys.getlocale()` 's value is 
![20200427094425](https://user-images.githubusercontent.com/43084101/80326620-f61a0500-886b-11ea-8adf-6914c9666519.png)

**Comment by ZHULOO** [comment] 2020-04-27 01:56
When the `main = "English title"`, there will be no `warnings()`.

**Comment by randy3k** [comment] 2020-04-27 02:14
Could you test it with the regular terminal in vscode rather than the R terminal?

**Comment by randy3k** [comment] 2020-04-27 02:22
I could reproduce it with the terminal by "Create R terminal". But it works fine if I open radian in a regular terminal.

**Comment by ZHULOO** [comment] 2020-04-27 02:27
![20200427102408](https://user-images.githubusercontent.com/43084101/80328228-52335800-8871-11ea-87bf-d87e03e3fe60.png)
Yes ,When I try to open radian in a regular terminal, it works fine, and the graphics window is independent. I also only reproduce it with the terminal by "Create R terminal".

**Comment by randy3k** [comment] 2020-04-27 02:40
I would only say that the issue belongs to `vscode-R`. I have no idea how it happens though.

**Comment by renkun-ken** [comment] 2020-04-27 02:41
Maybe the text vscode-R sends to radian has some encoding problem in this case? @andycraig any idea?

**Comment by randy3k** [comment] 2020-04-27 02:43
I believe it is related to how the process was launched. Maybe some variables or whatever was not passed to downstream.

**Comment by renkun-ken** [comment] 2020-04-27 02:50
Yes, the startup env is very likely to be the cause too.

**Comment by ZHULOO** [comment] 2020-04-27 02:51
> Maybe the text vscode-R sends to radian has some encoding problem in this case? @andycraig any idea?

OK, When it works fine in the indenpendent radian terminal, may be it's the `vscode-R` 's encoding problem. Thank you all the same!

**Comment by randy3k** [comment] 2020-04-27 03:00
I disabled the session watcher and it workes again with the R terminal. It turns out that we didn't trigger the `plot` warning while using the regular terminal.

In a regular terminal, I would reproduce the error when I source the script file.
```
r$> source("c:\\Users/vagrant/.vscode-R/init.R")
Warning message:
In as.POSIXlt.POSIXct(x, tz) : unable to identify current timezone 'C':
please set environment variable 'TZ'

r$> plot(0, main = "床前明月光")
There were 15 warnings (use warnings() to see them)

r$>
```

**Comment by randy3k** [comment] 2020-04-27 03:08
It doesn't seem to be a particular issue of radian. It seems to be a problem of R  and the script itself. For instance, I could use RGui.exe to reproduce the errors.

```
> Sys.setenv(TERM_PROGRAM = "vscode")
> source("c:/users/vagrant/.vscode-R/init.R")
Warning message:
In as.POSIXlt.POSIXct(x, tz) : unable to identify current timezone 'C':
please set environment variable 'TZ'
> plot(0, main = "床前明月光")
There were 15 warnings (use warnings() to see them)
```

**Comment by randy3k** [comment] 2020-04-27 03:11
@ZHULOO I suggest you moving this issue to `vscode-R` and continuing the discussion there.

closed, upstream issue.

**Comment by ZHULOO** [comment] 2020-04-27 03:12
OK, thank you!

**Closed by randy3k** 2020-04-27 03:11 UTC

**Comment by renkun-ken** [comment] 2020-04-27 03:47
I could also reproduce @randy3k's observation on Ubuntu. Let me take a closer look on this. It'd be nice that the discussion could be moved to vscode-R.

**Comment by ZHULOO** [comment] 2020-04-27 03:58
But how to move the discussion to vscode-R?

**Comment by randy3k** [comment] 2020-04-27 04:01
Just open a new thread and link to this page.
